// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cwvnkezfnyfkdltebuna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3dm5rZXpmbnlma2RsdGVidW5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MjY4MjMsImV4cCI6MjA1OTIwMjgyM30.sxm_DXsFKjZcbREieJJSzB_ocYcuLpgKIP849AYrN8U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);